### ISSUE TITLE
save function does not work properly

### ISSUE THREAD

**Issue by chenxiang-lin** [douglaslab/cadnano2#25]
caDNAno quits unexpected when saving a file. Initial saving was successful, but subsequent saving led the program to crush. 

Traceback (most recent call last):
  File "c:\virtualenvs\cn24x\lib\site-packages\cadnano2\controllers\documentcontroller.py", line 765, in writeDocumentToFile
    with open(filename, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\virtualenvs\cn24x\lib\site-packages\cadnano2\controllers\documentcontroller.py", line 323, in actionSaveSlot
    self.writeDocumentToFile()
  File "c:\virtualenvs\cn24x\lib\site-packages\cadnano2\controllers\documentcontroller.py", line 769, in writeDocumentToFile
    flags = Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint | Qt.WindowType.Sheet
AttributeError: type object 'Qt' has no attribute 'Dialog'

When starting caDNAno2 in an elevated command prompt (run as administrator), saving a file after the initial save create a file named C in C:\Windows\System32

I am running v2.4.3 in Windows environment.

**Comment by chenxiang-lin** [comment]
After upgrading to v2.4.4 this problem persists.

**Comment by sdouglas** [comment]
> After upgrading to v2.4.4 this problem persists.

I’ll look into this, but unfortunately don’t have an active Windows machine at the moment, so it may take some time.

**Comment by erdabravest2001** [comment]
hi there has this issue been fixed yet?
